spring.application.name=RideShare
spring.datasource.url=jdbc:postgresql://localhost:5432/rideshare_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.client.registration.google.client-id=1018809792253-fo3sdvtnou53nm7n445cc39ek7isg91s.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,email,profile
