CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     full_name VARCHAR(255),
                                     phone VARCHAR(255),
                                     email VARCHAR(255) NOT NULL UNIQUE,
                                     password VARCHAR(255) NOT NULL,
                                     avatar TEXT,
                                     role VARCHAR(255) DEFAULT 'USER',
                                     last_login_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ride (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    from_city VARCHAR(255),
                                    from_country VARCHAR(255),
                                    to_city VARCHAR(255),
                                    to_country VARCHAR(255),
                                    date DATE,
                                    seats INTEGER NOT NULL,
                                    price NUMERIC(10, 2),
                                    driver_name VARCHAR(255),
                                    driver_avatar TEXT,
                                    car_model VARCHAR(255),
                                    dep_time TIME,
                                    arr_time TIME,
                                    from_lat DOUBLE PRECISION,
                                    from_lng DOUBLE PRECISION,
                                    to_lat DOUBLE PRECISION,
                                    to_lng DOUBLE PRECISION,
                                    driver_id BIGINT,

                                    CONSTRAINT fk_ride_user
                                        FOREIGN KEY (driver_id)
                                            REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS bookings (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        ride_id BIGINT NOT NULL,
                                        passenger_id BIGINT NOT NULL,
                                        seats_booked INTEGER,
                                        payment_method VARCHAR(255),
                                        status VARCHAR(255) DEFAULT 'PENDING',
                                        pickup_location VARCHAR(255),
                                        passenger_note TEXT,

                                        CONSTRAINT fk_bookings_ride
                                            FOREIGN KEY (ride_id)
                                                REFERENCES ride(id),

                                        CONSTRAINT fk_bookings_passenger
                                            FOREIGN KEY (passenger_id)
                                                REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS notifications (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             recipient_id BIGINT NOT NULL,
                                             booking_id BIGINT,
                                             type VARCHAR(255) NOT NULL,
                                             title VARCHAR(255) NOT NULL,
                                             message TEXT,
                                             read BOOLEAN NOT NULL DEFAULT false,
                                             created_at TIMESTAMP DEFAULT NOW(),

                                             CONSTRAINT fk_notifications_recipient
                                                 FOREIGN KEY (recipient_id)
                                                     REFERENCES users(id),

                                             CONSTRAINT fk_notifications_booking
                                                 FOREIGN KEY (booking_id)
                                                     REFERENCES bookings(id)
);

CREATE TABLE IF NOT EXISTS messages (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        sender_id BIGINT NOT NULL,
                                        receiver_id BIGINT NOT NULL,
                                        content TEXT NOT NULL,
                                        read BOOLEAN NOT NULL DEFAULT false,
                                        created_at TIMESTAMP DEFAULT NOW(),

                                        CONSTRAINT fk_messages_sender
                                            FOREIGN KEY (sender_id)
                                                REFERENCES users(id),

                                        CONSTRAINT fk_messages_receiver
                                            FOREIGN KEY (receiver_id)
                                                REFERENCES users(id)
);